### ISSUE TITLE
Page 3

### ISSUE THREAD

**Issue by akshit-bhutani-19** [Akki019/DevopsLab_RockPaperScissor#12]
Adjust box.
Rock papar text in middle.
Background add.
Winner size increase.
Next game button set.

**Comment by Bhavesh-Kapur** [comment]
changed box styling 
added new set of images. 
Changed the style of the buttons.

**Comment by akshit-bhutani-19** [comment]
All good now.
Add bg

**Comment by Bhavesh-Kapur** [comment]
added background img ref. #23
